on:
  workflow_dispatch:

jobs:
  main:
    name: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      sha256-lin: ${{ steps.sha256.outputs.sha256-ubuntu-latest }}
      sha256-mac: ${{ steps.sha256.outputs.sha256-macos-latest }}
      sha256-win: ${{ steps.sha256.outputs.sha256-windows-latest }}
    steps:
      - uses: actions/checkout@v2
      - uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - run: jar --create --file a.jar --date 2022-09-20T00:00Z LICENSE README.md
      - id: sha256
        shell: bash
        run: |
          SHA256=$(sha256sum a.jar)
          echo $SHA256
          echo "::set-output name=sha256-${{ matrix.os }}::$SHA256"
  compare:
    runs-on: ubuntu-latest
    needs: main
    steps:
    - run: echo Linux SHA256 ${{needs.main.outputs.sha256-lin}}
    - run: echo MacOS SHA256 ${{needs.main.outputs.sha256-mac}}
    - run: echo WinOS SHA256 ${{needs.main.outputs.sha256-win}}
